final_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from sherlock.views import IndexView, UserCreateView, ProfileDetailView, MyProfileDetailView,\
                           AboutUpdateView, ContactUsView, SendEmailView,\
                           AboutUsView, ImageAddView, ImageUpdateView,\
                           ImageDeleteView, ProfileUpdateView, ImageAllView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^$', IndexView.as_view(), name="index_view"),
    url(r'^admin/', admin.site.urls),
    url(r'^messages/', include('django_messages.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^create_user/$', UserCreateView.as_view(), name="user_create_view"),
    url(r'^accounts/profile/$', MyProfileDetailView.as_view(), name="my_profile_detail_view"),
    url(r'^accounts/profile/(?P<pk>\d+)/$', ProfileDetailView.as_view(), name="profile_detail_view"),
    url(r'^profile/update/(?P<pk>\d+)/$', ProfileUpdateView.as_view(), name='profile_update_view'),
    url(r'^image/$', ImageAllView.as_view(), name='image_all_view'),
    url(r'^image/add/$', ImageAddView.as_view(), name='image_add_view'),
    url(r'^image/update/(?P<pk>\d+)/$', ImageUpdateView.as_view(), name='image_update_view'),
    url(r'^image/delete/(?P<pk>\d+)/$', ImageDeleteView.as_view(), name='image_delete_view'),
    url(r'^about/update/(?P<pk>\d+)/$', AboutUpdateView.as_view(), name='about_update_view'),
    url(r'^contact_us/$', ContactUsView.as_view(), name='contact_us_view'),
    url(r'^send_email/$', SendEmailView.as_view(), name='send_email_view'),
    url(r'^about_us/$', AboutUsView.as_view(), name="about_us_view"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sherlock/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse


@receiver(post_save, sender='auth.User')
def create_user_profile(**kwargs):
    created = kwargs.get('created')
    instance = kwargs.get('instance')
    if created:
        Profile.objects.create(user=instance)
        About.objects.create(user=instance)


class Profile(models.Model):
    user = models.OneToOneField('auth.User')
    picture = models.FileField(upload_to='profile_img', blank=True)
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50)
    gender = models.CharField(max_length=25, blank=True)
    joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user.id)

    @property
    def get_absolute_url(self, **kwargs):
        return reverse('profile_detail_view', kwargs={'pk': self.id})

    @property
    def profile_pic(self):
        if self.picture:
            return self.picture.url
        return "https://s3.amazonaws.com/tdh-des/images/picture.png"

    @property
    def get_year(self):
        year = self.joined.year
        return 'Joined in {}'.format(year)

    @property
    def get_about(self):
        return About.objects.filter(user=self.user)

    @property
    def get_relative(self):
        return Relative.objects.filter(user=self.user)

    @property
    def get_one_about(self):
        return About.objects.get(user=self.user)

    @property
    def get_image(self):
        return Image.objects.filter(user=self.user)

    @property
    def cap_first_name(self):
        return Profile.objects.get(user=self.user).first_name.title()

    @property
    def cap_last_name(self):
        return Profile.objects.get(user=self.user).last_name.title()

    @property
    def cap_full_name(self):
        return "{} {}".format(self.cap_first_name, self.cap_last_name)

class About(models.Model):
    GENDER = [
        ('Male', 'Male'),
        ('Female', 'Female')
    ]

    EYE_COLOR = [
        ('Black', 'Black'),
        ('Blue', 'Blue'),
        ('Brown', 'Brown'),
        ('Gray', 'Gray'),
        ('Green', 'Green'),
        ('Hazel', 'Hazel'),
        ('Other', 'Other')
    ]

    FAMILY = [
        ('Cousin', 'Cousin'),
        ('Child', 'Child'),
        ('Parent', 'Parent'),
        ('Sibling', 'Sibling'),
        ('Aunt', 'Aunt'),
        ('Uncle', 'Uncle'),
        ('Grandparent', 'Grandparent')
    ]

    user = models.OneToOneField('auth.User')
    biography = models.TextField(blank=True)
    birthdate = models.DateField(null=True, blank=True)
    city_of_birth = models.CharField(max_length=255, blank=True)
    state_of_birth = models.CharField(max_length=150, blank=True)
    country_of_birth = models.CharField(max_length=255, blank=True)
    sex_at_birth = models.CharField(max_length=10, choices=GENDER, blank=True)
    eye_color = models.CharField(max_length=10, choices=EYE_COLOR, blank=True)
    mother_first_name = models.CharField(max_length=150, blank=True)
    mother_maiden_name = models.CharField(max_length=150, blank=True)
    mother_last_name = models.CharField(max_length=150, blank=True)
    father_first_name = models.CharField(max_length=150, blank=True)
    father_last_name = models.CharField(max_length=150, blank=True)
    birth_hospital = models.CharField(max_length=150, blank=True)
    searching_for = models.CharField(max_length=20, choices=FAMILY, blank=True)

    # def __str__(self):
    #     return self.biography

    @property
    def get_images(self):
        return Image.objects.filter(user=self.user)


class Relative(models.Model):
    user = models.ForeignKey('auth.User')
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    relationship = models.CharField(max_length=30, blank=True)
    birth_year = models.IntegerField(null=True)
    unique_id = models.CharField(max_length=100, blank=True)
    location = models.TextField(blank=True)
    family_surnames = models.TextField(blank=True)
    similarity = models.CharField(max_length=50, blank=True)

    # def __str__(self):
    #     return self.user.username


class Image(models.Model):
    user = models.ForeignKey('auth.User')
    picture = models.FileField(upload_to='album_img', blank=True)
    description = models.CharField(max_length=150, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    @property
    def image_url(self):
        if self.picture:
            return self.picture.url
        # return 'http://www.metrovancouver.org/services/parks/reservable-facilities/FacilityPhotos/no-picture.gif'

    @property
    def get_user_image(self):
        return Image.objects.filter(user=self.user)

sherlock/forms.py
from django import forms
from django.core.mail import send_mail
from haystack.forms import SearchForm


class ContactForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.CharField(max_length=50)
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        name = self.cleaned_data["name"]
        email = self.cleaned_data["email"]
        message = self.cleaned_data["message"]
        subject = "Contact Submission Form!"
        body = """
        Hey Guys! You got a new contact form submission:
        From: {}
        At: {}
        Message: {}
        """.format(name, email, message)
        recipient_list = ["tdhdesapp@gmail.com"]
        send_mail(subject, body, 'Do Not Reply <do_not_replay@domain.com>', recipient_list)


class BirthdateSearchForm(SearchForm):
    birthdate = forms.DateField(required=False)

    def search(self):
        sqs = super(BirthdateSearchForm, self).search()

        if not self.is_valid():
            return self.no_query_found()

        if self.cleaned_data['birthdate']:
            sqs = sqs.filter(birthdate=self.cleaned_data['birthdate'])

        return sqs

sherlock/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, DeleteView
from django.views.generic.edit import CreateView, UpdateView, FormView
from django.contrib.auth.forms import UserCreationForm, User
from django.urls import reverse_lazy, reverse
from rest_framework.response import Response
from sherlock.forms import ContactForm, BirthdateSearchForm
from rest_framework.views import APIView
from sherlock.models import Profile, About, Relative, Image
from haystack.generic_views import FacetedSearchView
from haystack.query import SearchQuerySet
from haystack.utils import Highlighter
from haystack.forms import SearchForm
from django.core.paginator import InvalidPage, Paginator
from django.conf import settings
from django.core.mail import send_mail


class UserCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy("login")


class IndexView(TemplateView):
    template_name = "index.html"


class ProfileDetailView(DetailView):
    model = Profile


class MyProfileDetailView(ProfileDetailView):

    def get_object(self):
        return self.request.user.profile


class ProfileUpdateView(UpdateView):
    model = Profile
    # success_url = reverse_lazy('profile_detail_view')
    fields = ('picture', 'first_name', 'middle_name', 'last_name', 'gender', )
    success_url = reverse_lazy('my_profile_detail_view')

    def get_queryset(self):
        return Profile.objects.filter(user=self.request.user)


class AboutUpdateView(UpdateView):
    model = About
    success_url = reverse_lazy('profile_detail_view')
    fields = ('birthdate', 'city_of_birth', 'state_of_birth',
              'country_of_birth', 'sex_at_birth', 'eye_color', 'mother_first_name', 'mother_maiden_name',
              'mother_last_name', 'father_first_name', 'father_last_name', 'birth_hospital', 'searching_for',
              'biography',)

    def get_queryset(self):
        return About.objects.filter(user=self.request.user)

    def get_success_url(self, **kwargs):
        return reverse_lazy('profile_detail_view', args=[int(self.kwargs['pk'])])


class ContactUsView(TemplateView):
    template_name = "contact.html"

    def get_context_data(self):
        context = super().get_context_data()
        context["form"] = ContactForm()
        return context


class SendEmailView(FormView):
    form_class = ContactForm
    success_url = reverse_lazy("index_view")

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class BirthdateSearchView(SearchForm):
    form_class = BirthdateSearchForm


class AboutUsView(TemplateView):
    template_name = "about.html"


class ImageAllView(TemplateView):
    template_name = "images.html"

    def get_context_data(self):
        context = super().get_context_data()
        context["image"] = Image.objects.all()
        return context


class ImageAddView(CreateView):
    model = Image
    fields = ('picture', 'description', )

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self, *args, **kwargs):
        return reverse('profile_detail_view', args=[self.request.user.profile.id])


class ImageUpdateView(UpdateView):
    model = Image
    fields = ('picture', 'description', )

    def get_queryset(self):
        return Image.objects.filter(user=self.request.user)

    def get_success_url(self, *args, **kwargs):
        return reverse('profile_detail_view', args=[self.request.user.profile.id])


class ImageDeleteView(DeleteView):
    model = Image
    fields = ('picture', 'description', )

    def get_queryset(self):
        return Image.objects.filter(user=self.request.user)

    def get_success_url(self, *args, **kwargs):
        return reverse('profile_detail_view', args=[self.request.user.profile.id])

templates/sherlock/about_form.html
{% extends 'base.html' %}

{% block content %}
<div class="ui container">
  <div class="ui grid">
    <div class="ui sixteend wide column">
      <div class="ui teal raised segment">
        <form class="ui small form" action="" method="post">
          {% csrf_token %}
          {{form.as_p}}
        <input class="ui teal submit button" type="submit" name="" value="Submit">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/sherlock/image_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="ui container">
  <div class="ui grid">
    <div class="ui sixteen wide column">
      <div class="ui teal form segment">
        <form class="" action="" method="post">
          {% csrf_token %}
          <div class="content">
            <p>
              You are about to permanently delete this photo: <strong>{{object.picture}}</strong>.
              &nbsp;Are you sure you want to proceed?
            </p>
            <input class="ui green icon button" type="submit" name="" value="Yes">

            <button class="ui red icon button" type="button" name="">
              <a class="ui-white-link" href="{% url 'profile_detail_view' user.id %}">No</a></button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/sherlock/image_form.html
{% extends 'base.html' %}

{% block content %}
<div class="ui container">
  <div class="ui grid">
    <div class="ui sixteen wide column">
      <div class="ui teal form segment">
        <form class="" action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <input class="ui blue button" type="submit" name="" value="Save">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/sherlock/profile_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}

{% block content %}

{% if request.user.is_authenticated %}
<div class="ui-p-container">
    <div class="ui equal width grid">
      <div class="five wide column">
            <div class="ui card">
              <div class="image">
                <img src="{{object.profile_pic}}" alt="Profile Photo" />
              </div>
              <div class="content">
                <div class="header">{{object.first_name|capfirst}} {{object.last_name|capfirst}}</div>
                <div class="meta">
                  <a></a>
                </div>
                <div class="description">
                </div>
              </div>
              <div class="extra content">
                <span class="right floated">
                  {{object.get_year}}
                  <br>
                  {% if object.user == request.user %}

                  <a href="{% url 'messages_inbox' %}"><i class="large blue mail outline icon"></i></a>
                    {% load inbox %}
                    <a class="ui mini teal circular label">{% inbox_count %}</a>
                  {% endif %}
                </span>
                <span>
                  <i class="user icon"></i>
                  {{object.user.username}} <br>
                  {% if object.user == request.user %}
                  <a href="{% url 'profile_update_view' object.id %}"></i><i class="large blue edit icon"></i></a>
                  {% endif %}
                </span>
              </div>
            </div>
          </div>
        <div class="eleven wide column">
          <div class="ui-- raised very padded text container segment">
            <h2 class="ui left floated header"><i class="user icon"></i>About</h2>
              {% if object.user == request.user %}
            <h5 class="ui right floated header"><a href="{% url 'about_update_view' object.user.profile.id %}"><i class="extra large edit icon"></i></a></h5>
              {% else %}
            <h5 class="ui right floated header"><a class="ui teal button" href="{% url 'messages_compose' %}?recipient={{object.user.username}}">
              <i class="write icon"></i>Message {{object.user.username}}</a></h5>
              {% endif %}

            <br>
            &nbsp;
        <div class="ui divider"></div>
          <div class="ui four column grid">
        {% for thing in object.get_about %}
            <div class="column">
              <div class="ui items">
                <div class="item">
                  <div class="content">
                    <div class="header">Birthday</div>
                      <div class="meta">
                        <p>{{thing.birthdate}}</p>
                      </div>
                    <div class="header">Age</div>
                      <div class="meta">
                        <p>{{thing.birthdate|timesince}}</p>
                      </div>
                    <div class="header">Birth City</div>
                      <div class="meta">
                        <p>{{thing.city_of_birth|default:"n/a"}}</p>
                      </div>
                    <div class="header">Birth State</div>
                      <div class="meta">
                        <p>{{thing.state_of_birth|default:"n/a"}}</p>
                      </div>
                  </div>
                </div>
              </div>
            </div>
              <div class="column">
                <div class="ui items">
                  <div class="item">
                    <div class="content">
                        <div class="header">Birth Country</div>
                          <div class="meta">
                            <p>{{thing.country_of_birth|default:"USA"}}</p>
                          </div>
                        <div class="header">Birth Hospital</div>
                          <div class="meta">
                            <p>{{thing.birth_hospital|default:"n/a"}}</p>
                          </div>
                        <div class="header">Birth Gender</div>
                          <div class="meta">
                            <p>{{thing.get_sex_at_birth_display|default:"n/a"}}</p>
                          </div>
                        <div class="header">Eye Color</div>
                          <div class="meta">
                            <p>{{thing.get_eye_color_display|default:"n/a"}}</p>
                          </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="column">
                <div class="ui items">
                  <div class="item">
                    <div class="content">
                        <div class="header">Mother's First Name</div>
                          <div class="meta">
                            <p>{{thing.mother_first_name|default:"n/a"}}</p>
                          </div>
                        <div class="header">Mother's Maiden Name</div>
                          <div class="meta">
                            <p>{{thing.mother_maiden_name|default:"n/a"}}</p>
                          </div>
                        <div class="header">Mother's Last Name</div>
                          <div class="meta">
                            <p>{{thing.mother_last_name|default:"n/a"}}</p>
                          </div>

                    </div>
                  </div>
                </div>
              </div>
              <div class="column">
                <div class="ui items">
                  <div class="item">
                    <div class="content">
                      <div class="header">Father's First Name</div>
                        <div class="meta">
                          <p>{{thing.father_first_name|default:"n/a"}}</p>
                        </div>
                      <div class="header">Father's Last Name</div>
                        <div class="meta">
                          <p>{{thing.father_last_name|default:"n/a"}}</p>
                        </div>
                      <div class="header">Searching For My:</div>
                      <div class="meta">
                        <p>{{thing.get_searching_for_display|default:"n/a"}}</p>
                      </div>
                      <br>
                      <br>
                      <br>
                      <br>
                      <br>
                    </div>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
      <div class="sixteen wide column">
        <div class="ui--- raised text container segment">
            <h2 class="ui center aligned icon header">
              <i class="pied piper hat icon"></i>Biography</h2>
            <div class="ui divider"></div>
              <p>
                {{thing.biography}}
              </p>
        </div>
      </div>


          {% endfor %}

  <div class="ui divider"></div>
  <!-- <a href="{% url 'image_all_view' %}">All images</a> -->
  {% if object.user == request.user %}
  <a class="ui blue right floated basic button" href="{% url 'image_add_view' %}"><i class="ui camera icon"></i>Upload Image</a>

  {% endif %}
    <div class="ui grid">
        {% for image in object.get_image %}
          <div class="four wide column">
            <div class="ui medium image">
            {% if object.user == request.user %}
            <div class="ui dimmer">
              <div class="content">
                <div class="center">
                  <h2 class="ui inverted header"></h2>
                  <div class="ui primary button">
                    <a class="ui-white-link" href="{% url 'image_update_view' image.id %}">Edit</a></div>
                  <div class="ui button">
                    <a href="{% url 'image_delete_view' image.id %}">Delete</a></div>
                </div>
              </div>
            </div>
            {% endif %}
            <img class="ui medium image" src="{{image.image_url}}" alt="">
          </div>

            {{image.description}}
          </div>
        {% endfor %}

    </div>
    <br>
<div class="ui divider"></div>
  <div class="ui grid">
    <div class="column">
      <div class="ui floating info message">
        <i class="close icon"></i>
        <div class="content">
          <div class="header">
            Import your 23andMe Relative Results!
          </div>
            <p>
              Connecting with 23andMe will import your top ten family relationship results, as listed in your 23andMe profile.
              This will allow other users to see DNA relational matches-which might help you connect!
            </p>
            <p>
              Imported information includes:
              First Name, Last Name, Relationship, Birth Year, DNA Similarity, Location, and Family Surnames.
            </p>
            <p>
              You only need to connect once to import all of your data, unless 23andMe updates your results.
            </p>
          </div>
          <div class="logo">
            <a class="item" href="{% url 'social:begin' 'twentythreeandme' %}">
            <img src="{% static 'images/23andme.png' %}" alt="sync with 23 and me"/></a>
          </div>
        </div>
    </div>

  </div>
  <div class="ui grid">
    <div class="column">
      {% if object.get_relative %}
      <h2 class="twentythree"> 23andMe Relative Results</h2>
      <div class="ui compact teal table">
          <table>
            <thead>
              <tr class="center aligned">
                <th>First Name</th>
                <th>Last Name</th>
                <th>Relationship</th>
                <th>Birth Year</th>
                <th>DNA Similarity</th>
                <th>Location</th>
                <th>Family Surnames</th>
                </tr>
            </thead>
            <tbody class="center aligned">
              {% for thing in object.get_relative %}
                <tr>
                  <td>
                    {{thing.first_name|title}}
                  </td>
                  <td>
                    {{thing.last_name|title}}
                  </td>
                  <td>
                    {{thing.relationship}}
                  </td>
                  <td>
                    {{thing.birth_year}}
                  </td>
                  <td>
                    {{thing.similarity}}
                  </td>
                  <td>
                    {{thing.location|cut:"]"|cut:"["|cut:"'"}}
                  </td>
                  <td>
                    {{thing.family_surnames|cut:"]"|cut:"["|cut:"'"}}
                  </td>

                </tr>
              {% endfor %}
            </tbody>

          </table>
          {% endif %}
        </div>
    </div>
</div>


</div>
{% endif %}
{% endblock %}
{% block javascript %}
<script type="text/javascript">
    $('.ui.dropdown')
    .dropdown()
    ;

    $('.message .close')
    .on('click', function() {
    $(this)
      .closest('.message')
      .transition('fade')
    ;
      })
    ;
    $('.dimmer')
      .dimmer({
        on: 'hover'
      })
        ;

      $('.teal.button')
        .hover(function(){
          $(this)
          .transition('pulse');
        });

      $('.ui.blue')
        .hover(function(){
          $(this)
          .transition('pulse');
        });
</script>

{% endblock %}

// $('.teal.button')
// .on('click', function(){
//   $(this)
//   .transition('pulse');
//
// })

templates/sherlock/profile_form.html
{% extends 'base.html' %}

{% block content %}
  {% if request.user.is_authenticated %}
    {% if object.user == request.user %}
  <div class="ui container">
    <div class="ui grid">
      <div class="ui sixteen wide column">
          <div class="ui teal raised segment">
              <form class="ui small form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="ui teal submit button" type="submit" name="" value="Update">
              </form>
          </div>
      </div>
    </div>
  </div>
    {% endif %}
  {% endif %}
{% endblock %}

templates/sherlock/profile_list.html
{% extends 'base.html' %}

{% block content %}
<div class="ui-p-container">
  {% for image in object.get_image %}
    {{image.image_url}}
  {% endfor %}
</div>

{% endblock %}